import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React from 'react'

import { gql, GraphQLClient } from 'graphql-request';
import { useSpeechSynthesis } from 'react-speech-kit';



const GetWordList = gql`
query WordLists {
    wordLists {
      id
      slug
      userName
      words
    }
  }
`;

export const getStaticProps = async (context) => {
    const hygraph = new GraphQLClient(process.env.HYGRAPH_ENDPOINT)

    const { wordLists } = await hygraph.request(`
    {
        wordLists {
            id
            slug
            userName
            words
          }
    }`)

    return {
        props: {
            wordLists
        }
    }
}

export default function Quiz({ wordLists }) {

  const wordArray = wordLists[0].words.split(';');
  const [value, setValue] = React.useState(wordArray[0]);
  const { speak } = useSpeechSynthesis();
  const [index, setIndex] = React.useState(0);



  return (
    <div className={styles.container}>
      <Head>
        <title>Spelling with CDS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Time to <span className="text-blue-600">Spell!</span>
        </h1>

        <div className={"grid-cols-1 text-center"}>
          <code>{wordLists[0].words}</code>
          <div>
            <button onClick={() => {
                    speak({ text: value });
                    setIndex(index + 1 < 3 ? index + 1 : 0);
                    setValue(wordArray[index]);
                }}
                className={"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"}
                >
                    Speak
            </button>
          </div>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://ryan-james.dev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by Ryan James
        </a>
      </footer>
    </div>
  )
}
